title = "Sandwich"  # From Git
gitRepoUrl = "https://github.com/data-oriented-house/sandwich" # From Git

gitSourceBranch = "main"
changelog = true

[home]
enabled = true
includeReadme = false

[navbar.logo]
src = "favicon.ico"

[[home.features]]
title = "Extensible and Composable"
description = "Because all logic is separated from data, your jobs are extensible and composable right from the start! This enables elegant solutions to complex problems often introduced in ECS or loading patterns!"
# image = "/PuzzlePieces.png"

[[home.features]]
title = "Job Scheduling"
description = "Sandwich allows you to easily order jobs in your experiences via dependencies and perform logic on intervals."
image = "/SandwichLogo.png"

[[home.features]]
title = "Lightweight and Effective"
description = "The code is simple, short, and effective. Your project won't be bogged down by a large library; Sandwich is just over 100 lines!"
# image = "/Lightweight.png"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

# From git:
organizationName = "Data-Oriented-House"
projectName = "Sandwich"
url = "https://data-oriented-house.github.io"
baseUrl = "/Sandwich/"
tagline = "Roblox's lightweight scheduler"

[navbar]
# hideableSidebar = true

[footer]
style = "dark"
copyright = "Copyright © 2023 SolarScuffle-Bot. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"